- Add support for Python 3.12.  - Drop support for Python 3.7.
zopefoundation/zc.recipe.testrunner pull request #17
Opened 2024-07-15 06:34 UTC by icemac

Fix test in GHA.

2024-07-15 06:45 UTC, icemac commented
Failed to pin `setuptools` to `< 69`: It gets ignored an `setuptools==70.1.0` is used for most Python versions. (Python 3.12 succeeds while using `setuptools==70.3.0`, which is also strange.)

So let's wait for https://github.com/buildout/buildout/pull/649 to be merged and released, which allows `setuptools >= 70`.

2024-09-26 07:20 UTC, dataflake requested changes
What's with that setuptools pin in setup.py and why `< 69`?

2024-09-26 07:20 UTC, dataflake commented on CHANGES.rst
> +- Pin ``setuptools < 69``, as newer versions break ``zc.buildout``.
```suggestion
- Pin ``setuptools < 74``, as newer versions break ``zc.buildout``.
```

2024-09-26 07:20 UTC, dataflake commented on setup.py
> +        'setuptools < 69',
```suggestion
        'setuptools < 74',
```

2024-09-26 08:54 UTC, dataflake approved these changes

2024-09-26 08:55 UTC, dataflake commented
I removed the pin (and change log entry for it) and everything's still green.

2024-09-27 07:14 UTC, icemac commented
Thank you for reviewing this PR. 😃

2024-09-27 07:14 UTC, merged